import React from 'react'
import Nav from './Nav'
import Footer from './Footer'
import useForm from '../../utils/useForm'
import { useHistory } from 'react-router-dom'
import { Icon, Label, Menu, Table } from 'semantic-ui-react'

function HandicapTracker() {

  const history = useHistory()

  const [registerErrors, setRegisterErrors] = React.useState(false)

  const { formdata,  handleChange } = useForm({
    playerOne: '', 
    playerTwo: '',
    playerThree: '', 
    playerFour: '', 
    holeOneYardage: '',
    holeTwoYardage: '',
    holeThreeYardage: '',
    holeFourYardage: '',
    holeFiveYardage: '',
    holeSixYardage: '',
    holeSevenYardage: '',
    holeEightYardage: '',
    holeNineYardage: '',
    holeTenYardage: '',
    holeElevenYardage: '',
    holeTwelveYardage: '',
    holeThirteenYardage: '',
    holeFourteenYardage: '',
    holeFifteenYardage: '',
    holeSixteenYardage: '',
    holeSeventeenYardage: '',
    holeEighteenYardage: '',

    // name: '',
    // address: '',
    // city: '',
    // country: '',
    // continent: '',
    // description: '',
    // property_image: '',
    // is_available: '',
    // latitude: '',
    // longitude: '',
    // bathrooms: '',
    // bedrooms: '',
    // types: [],
    // owner: ''
  })

  return (
    <section>
      <Nav />
      <div className="about-content">
        <h1 className="about-header">Handicap Tracker</h1>
        <Table celled>
          <Table.Header>
            <Table.Row>
              <Table.HeaderCell>Hole</Table.HeaderCell>
              <Table.HeaderCell>1</Table.HeaderCell>
              <Table.HeaderCell>2</Table.HeaderCell>
              <Table.HeaderCell>3</Table.HeaderCell>
              <Table.HeaderCell>4</Table.HeaderCell>
              <Table.HeaderCell>5</Table.HeaderCell>
              <Table.HeaderCell>6</Table.HeaderCell>
              <Table.HeaderCell>7</Table.HeaderCell>
              <Table.HeaderCell>8</Table.HeaderCell>
              <Table.HeaderCell>9</Table.HeaderCell>
              <Table.HeaderCell>OUT</Table.HeaderCell>
              <Table.HeaderCell>10</Table.HeaderCell>
              <Table.HeaderCell>11</Table.HeaderCell>
              <Table.HeaderCell>12</Table.HeaderCell>
              <Table.HeaderCell>13</Table.HeaderCell>
              <Table.HeaderCell>14</Table.HeaderCell>
              <Table.HeaderCell>15</Table.HeaderCell>
              <Table.HeaderCell>16</Table.HeaderCell>
              <Table.HeaderCell>17</Table.HeaderCell>
              <Table.HeaderCell>18</Table.HeaderCell>
              <Table.HeaderCell>IN</Table.HeaderCell>
              <Table.HeaderCell>OUT</Table.HeaderCell>
              <Table.HeaderCell>TOTAL</Table.HeaderCell>
            </Table.Row>
          </Table.Header>

          <Table.Body>
            <Table.Row>
              <Table.HeaderCell>
                Yardage
              </Table.HeaderCell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwoYardage"
                  value={formdata.holeTwoYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThreeYardage"
                  value={formdata.holeThreeYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourYardage"
                  value={formdata.holeFourYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFiveYardage"
                  value={formdata.holeFiveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixYardage"
                  value={formdata.holeSixYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSevenYardage"
                  value={formdata.holeSevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEightYardage"
                  value={formdata.holeEightYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeNineYardage"
                  value={formdata.holeNineYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTenYardage"
                  value={formdata.holeTenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeElevenYardage"
                  value={formdata.holeElevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwelveYardage"
                  value={formdata.holeTwelveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThirteenYardage"
                  value={formdata.holeThirteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourteenYardage"
                  value={formdata.holeFourteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFifteenYardage"
                  value={formdata.holeFifteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixteenYardage"
                  value={formdata.holeSixteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSeventeenYardage"
                  value={formdata.holeSeventeenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEighteenYardage"
                  value={formdata.holeEighteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
            </Table.Row>
            <Table.Row>
            <Table.HeaderCell>
                Par
              </Table.HeaderCell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwoYardage"
                  value={formdata.holeTwoYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThreeYardage"
                  value={formdata.holeThreeYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourYardage"
                  value={formdata.holeFourYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFiveYardage"
                  value={formdata.holeFiveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixYardage"
                  value={formdata.holeSixYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSevenYardage"
                  value={formdata.holeSevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEightYardage"
                  value={formdata.holeEightYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeNineYardage"
                  value={formdata.holeNineYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTenYardage"
                  value={formdata.holeTenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeElevenYardage"
                  value={formdata.holeElevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwelveYardage"
                  value={formdata.holeTwelveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThirteenYardage"
                  value={formdata.holeThirteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourteenYardage"
                  value={formdata.holeFourteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFifteenYardage"
                  value={formdata.holeFifteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixteenYardage"
                  value={formdata.holeSixteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSeventeenYardage"
                  value={formdata.holeSeventeenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEighteenYardage"
                  value={formdata.holeEighteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
            </Table.Row>
            <Table.Row>
            <Table.HeaderCell>
                Index
              </Table.HeaderCell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwoYardage"
                  value={formdata.holeTwoYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThreeYardage"
                  value={formdata.holeThreeYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourYardage"
                  value={formdata.holeFourYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFiveYardage"
                  value={formdata.holeFiveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixYardage"
                  value={formdata.holeSixYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSevenYardage"
                  value={formdata.holeSevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEightYardage"
                  value={formdata.holeEightYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeNineYardage"
                  value={formdata.holeNineYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTenYardage"
                  value={formdata.holeTenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeElevenYardage"
                  value={formdata.holeElevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwelveYardage"
                  value={formdata.holeTwelveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThirteenYardage"
                  value={formdata.holeThirteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourteenYardage"
                  value={formdata.holeFourteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFifteenYardage"
                  value={formdata.holeFifteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixteenYardage"
                  value={formdata.holeSixteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSeventeenYardage"
                  value={formdata.holeSeventeenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEighteenYardage"
                  value={formdata.holeEighteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
            </Table.Row>
            <Table.Row>
            <Table.HeaderCell>
                Player 1
              </Table.HeaderCell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwoYardage"
                  value={formdata.holeTwoYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThreeYardage"
                  value={formdata.holeThreeYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourYardage"
                  value={formdata.holeFourYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFiveYardage"
                  value={formdata.holeFiveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixYardage"
                  value={formdata.holeSixYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSevenYardage"
                  value={formdata.holeSevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEightYardage"
                  value={formdata.holeEightYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeNineYardage"
                  value={formdata.holeNineYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTenYardage"
                  value={formdata.holeTenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeElevenYardage"
                  value={formdata.holeElevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwelveYardage"
                  value={formdata.holeTwelveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThirteenYardage"
                  value={formdata.holeThirteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourteenYardage"
                  value={formdata.holeFourteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFifteenYardage"
                  value={formdata.holeFifteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixteenYardage"
                  value={formdata.holeSixteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSeventeenYardage"
                  value={formdata.holeSeventeenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEighteenYardage"
                  value={formdata.holeEighteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
            </Table.Row>
            <Table.Row>
            <Table.HeaderCell>
                Player 2
              </Table.HeaderCell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwoYardage"
                  value={formdata.holeTwoYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThreeYardage"
                  value={formdata.holeThreeYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourYardage"
                  value={formdata.holeFourYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFiveYardage"
                  value={formdata.holeFiveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixYardage"
                  value={formdata.holeSixYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSevenYardage"
                  value={formdata.holeSevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEightYardage"
                  value={formdata.holeEightYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeNineYardage"
                  value={formdata.holeNineYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTenYardage"
                  value={formdata.holeTenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeElevenYardage"
                  value={formdata.holeElevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwelveYardage"
                  value={formdata.holeTwelveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThirteenYardage"
                  value={formdata.holeThirteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourteenYardage"
                  value={formdata.holeFourteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFifteenYardage"
                  value={formdata.holeFifteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixteenYardage"
                  value={formdata.holeSixteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSeventeenYardage"
                  value={formdata.holeSeventeenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEighteenYardage"
                  value={formdata.holeEighteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
            </Table.Row>
            <Table.Row>
            <Table.HeaderCell>
                Player 3
              </Table.HeaderCell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwoYardage"
                  value={formdata.holeTwoYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThreeYardage"
                  value={formdata.holeThreeYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourYardage"
                  value={formdata.holeFourYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFiveYardage"
                  value={formdata.holeFiveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixYardage"
                  value={formdata.holeSixYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSevenYardage"
                  value={formdata.holeSevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEightYardage"
                  value={formdata.holeEightYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeNineYardage"
                  value={formdata.holeNineYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTenYardage"
                  value={formdata.holeTenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeElevenYardage"
                  value={formdata.holeElevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwelveYardage"
                  value={formdata.holeTwelveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThirteenYardage"
                  value={formdata.holeThirteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourteenYardage"
                  value={formdata.holeFourteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFifteenYardage"
                  value={formdata.holeFifteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixteenYardage"
                  value={formdata.holeSixteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSeventeenYardage"
                  value={formdata.holeSeventeenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEighteenYardage"
                  value={formdata.holeEighteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
            </Table.Row>
            <Table.Row>
            <Table.HeaderCell>
                Player 4
              </Table.HeaderCell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwoYardage"
                  value={formdata.holeTwoYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThreeYardage"
                  value={formdata.holeThreeYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourYardage"
                  value={formdata.holeFourYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFiveYardage"
                  value={formdata.holeFiveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixYardage"
                  value={formdata.holeSixYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSevenYardage"
                  value={formdata.holeSevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEightYardage"
                  value={formdata.holeEightYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeNineYardage"
                  value={formdata.holeNineYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTenYardage"
                  value={formdata.holeTenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeElevenYardage"
                  value={formdata.holeElevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwelveYardage"
                  value={formdata.holeTwelveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThirteenYardage"
                  value={formdata.holeThirteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourteenYardage"
                  value={formdata.holeFourteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFifteenYardage"
                  value={formdata.holeFifteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixteenYardage"
                  value={formdata.holeSixteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSeventeenYardage"
                  value={formdata.holeSeventeenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEighteenYardage"
                  value={formdata.holeEighteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
            </Table.Row>
            <Table.Row>
            <Table.HeaderCell>
                Notes
              </Table.HeaderCell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwoYardage"
                  value={formdata.holeTwoYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThreeYardage"
                  value={formdata.holeThreeYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourYardage"
                  value={formdata.holeFourYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFiveYardage"
                  value={formdata.holeFiveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixYardage"
                  value={formdata.holeSixYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSevenYardage"
                  value={formdata.holeSevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEightYardage"
                  value={formdata.holeEightYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeNineYardage"
                  value={formdata.holeNineYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTenYardage"
                  value={formdata.holeTenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeElevenYardage"
                  value={formdata.holeElevenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeTwelveYardage"
                  value={formdata.holeTwelveYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeThirteenYardage"
                  value={formdata.holeThirteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFourteenYardage"
                  value={formdata.holeFourteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeFifteenYardage"
                  value={formdata.holeFifteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSixteenYardage"
                  value={formdata.holeSixteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeSeventeenYardage"
                  value={formdata.holeSeventeenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeEighteenYardage"
                  value={formdata.holeEighteenYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
              <Table.Cell>
                <input
                  className="input-cell"
                  placeholder=""
                  onChange={handleChange}
                  name="holeOneYardage"
                  value={formdata.holeOneYardage}
                />
              </Table.Cell>
            </Table.Row>
          </Table.Body>

          {/* <Table.Footer>
      <Table.Row>
        <Table.HeaderCell colSpan='3'>
          <Menu floated='right' pagination>
            <Menu.Item as='a' icon>
              <Icon name='chevron left' />
            </Menu.Item>
            <Menu.Item as='a'>1</Menu.Item>
            <Menu.Item as='a'>2</Menu.Item>
            <Menu.Item as='a'>3</Menu.Item>
            <Menu.Item as='a'>4</Menu.Item>
            <Menu.Item as='a' icon>
              <Icon name='chevron right' />
            </Menu.Item>
          </Menu>
        </Table.HeaderCell>
      </Table.Row>
    </Table.Footer> */}
        </Table>
        <button>Submit Scorecard</button>
      </div>
      <Footer />
    </section>
  )
}

export default HandicapTracker